// TurboCore — TEB Event Registry (Chapter 9)
//
// "Instead of allowing arbitrary event names, maintain a central registry.
//  This prevents duplicate event definitions, schema drift, and inconsistent
//  naming across teams."
//
// Every event type that TurboCore publishes is registered here with its
// full contract: owner, producer, consumers, schema, version, priority,
// classification, retention, and ordering guarantee.

import type {
  EventContract,
  EventCategory,
  EventStream,
  EventPriority,
  EventClassification,
  EventRetention,
} from "./types";

// ---------------------------------------------------------------------------
// The master event registry (~50 event contracts)
// ---------------------------------------------------------------------------

export const EVENT_REGISTRY: EventContract[] = [
  // ===== Business Events =====
  {
    eventType: "CUSTOMER.CREATED",
    name: "Customer Created",
    description: "A new customer registered on TurboPay.",
    category: "BUSINESS",
    stream: "system",
    priority: "HIGH",
    classification: "INTERNAL",
    owner: "Identity Domain",
    producer: "auth-service",
    consumers: ["wallet-service", "kyc-service", "analytics-service", "notification-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "FOREVER", reason: "Customer lifecycle audit" },
    requiredFields: ["userId", "email", "phone", "country"],
    optionalFields: ["referrer", "signupSource"],
    example: { userId: "usr_01H7...", email: "john@example.com", phone: "+234...", country: "NG" },
  },
  {
    eventType: "MERCHANT.CREATED",
    name: "Merchant Created",
    description: "A new merchant was onboarded.",
    category: "BUSINESS",
    stream: "merchant",
    priority: "HIGH",
    classification: "INTERNAL",
    owner: "Merchant Domain",
    producer: "merchant-service",
    consumers: ["wallet-service", "analytics-service", "notification-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "FOREVER", reason: "Merchant lifecycle audit" },
    requiredFields: ["merchantId", "businessName", "country"],
    optionalFields: ["category", "website"],
    example: { merchantId: "mer_01HD...", businessName: "Acme Ltd", country: "NG" },
  },
  {
    eventType: "ACCOUNT.UPDATED",
    name: "Account Updated",
    description: "Customer account details were updated.",
    category: "BUSINESS",
    stream: "system",
    priority: "MEDIUM",
    classification: "INTERNAL",
    owner: "Identity Domain",
    producer: "identity-service",
    consumers: ["analytics-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 5, reason: "Account change history" },
    requiredFields: ["userId", "changes"],
    optionalFields: ["actor"],
    example: { userId: "usr_01H7...", changes: { fullName: "John Doe" } },
  },
  {
    eventType: "PROFILE.UPDATED",
    name: "Profile Updated",
    description: "Customer profile was updated.",
    category: "BUSINESS",
    stream: "system",
    priority: "LOW",
    classification: "INTERNAL",
    owner: "Customer Domain",
    producer: "identity-service",
    consumers: ["analytics-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 3, reason: "Profile history" },
    requiredFields: ["userId"],
    optionalFields: ["changes"],
    example: { userId: "usr_01H7...", changes: { bio: "Updated bio" } },
  },

  // ===== Financial Events =====
  {
    eventType: "PAYMENT.CREATED",
    name: "Payment Created",
    description: "A new payment was initiated.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Payment Domain",
    producer: "payment-service",
    consumers: ["ledger-service", "risk-service", "analytics-service", "notification-service"],
    version: "v2",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Financial record — regulatory requirement" },
    requiredFields: [
      "transactionId",
      "userId",
      "amountMinor",
      "currency",
      "providerCode",
      "direction",
    ],
    optionalFields: ["merchantId", "paymentMethod", "metadata"],
    example: {
      transactionId: "txn_01H8...",
      userId: "usr_01H7...",
      amountMinor: 100000,
      currency: "NGN",
      providerCode: "paystack",
      direction: "INBOUND",
    },
  },
  {
    eventType: "PAYMENT.ROUTED",
    name: "Payment Routed",
    description: "A payment was routed to a provider.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "HIGH",
    classification: "INTERNAL",
    owner: "Payment Domain",
    producer: "routing-service",
    consumers: ["analytics-service", "audit-service"],
    version: "v1",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Routing decision audit" },
    requiredFields: ["transactionId", "providerCode", "score", "alternatives"],
    optionalFields: ["reason"],
    example: {
      transactionId: "txn_01H8...",
      providerCode: "paystack",
      score: 95,
      alternatives: ["flutterwave", "monnify"],
    },
  },
  {
    eventType: "PAYMENT.AUTHORIZED",
    name: "Payment Authorized",
    description: "Payment was authorized by the provider.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Payment Domain",
    producer: "orchestrator",
    consumers: ["ledger-service", "analytics-service"],
    version: "v1",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Financial record" },
    requiredFields: ["transactionId", "providerCode", "authCode"],
    optionalFields: ["amountMinor"],
    example: { transactionId: "txn_01H8...", providerCode: "paystack", authCode: "AUTH123" },
  },
  {
    eventType: "PAYMENT.COMPLETED",
    name: "Payment Completed",
    description: "Payment was successfully completed.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Payment Domain",
    producer: "orchestrator",
    consumers: [
      "ledger-service",
      "wallet-service",
      "analytics-service",
      "notification-service",
      "settlement-service",
      "merchant-service",
    ],
    version: "v2",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Financial record — regulatory requirement" },
    requiredFields: ["transactionId", "userId", "amountMinor", "currency", "providerCode"],
    optionalFields: ["merchantId", "feeMinor", "settledAt"],
    example: {
      transactionId: "txn_01H8...",
      userId: "usr_01H7...",
      amountMinor: 100000,
      currency: "NGN",
      providerCode: "paystack",
    },
  },
  {
    eventType: "PAYMENT.FAILED",
    name: "Payment Failed",
    description: "A payment failed.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Payment Domain",
    producer: "orchestrator",
    consumers: ["ledger-service", "risk-service", "analytics-service", "notification-service"],
    version: "v2",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Financial record — failure analysis" },
    requiredFields: ["transactionId", "userId", "errorCode", "errorMessage"],
    optionalFields: ["providerCode", "amountMinor", "retryable"],
    example: {
      transactionId: "txn_01H8...",
      userId: "usr_01H7...",
      errorCode: "INSUFFICIENT_FUNDS",
      errorMessage: "Card declined",
    },
  },
  {
    eventType: "TRANSFER.COMPLETED",
    name: "Transfer Completed",
    description: "A wallet-to-wallet or bank transfer completed.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Payment Domain",
    producer: "orchestrator",
    consumers: ["ledger-service", "wallet-service", "analytics-service", "notification-service"],
    version: "v1",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Financial record" },
    requiredFields: ["transactionId", "userId", "amountMinor", "currency", "direction"],
    optionalFields: ["recipientName", "recipientAccount"],
    example: {
      transactionId: "txn_01H8...",
      userId: "usr_01H7...",
      amountMinor: 50000,
      currency: "NGN",
      direction: "OUTBOUND",
    },
  },
  {
    eventType: "REFUND.CREATED",
    name: "Refund Created",
    description: "A refund was initiated.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Payment Domain",
    producer: "payment-service",
    consumers: ["ledger-service", "analytics-service", "notification-service"],
    version: "v1",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Financial record" },
    requiredFields: ["refundId", "transactionId", "amountMinor", "type"],
    optionalFields: ["reason"],
    example: {
      refundId: "rfd_01HI...",
      transactionId: "txn_01H8...",
      amountMinor: 50000,
      type: "FULL",
    },
  },
  {
    eventType: "REFUND.COMPLETED",
    name: "Refund Completed",
    description: "A refund was completed.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Payment Domain",
    producer: "orchestrator",
    consumers: ["ledger-service", "wallet-service", "analytics-service", "notification-service"],
    version: "v1",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Financial record" },
    requiredFields: ["refundId", "transactionId", "amountMinor"],
    optionalFields: ["providerRef"],
    example: { refundId: "rfd_01HI...", transactionId: "txn_01H8...", amountMinor: 50000 },
  },
  {
    eventType: "SETTLEMENT.COMPLETED",
    name: "Settlement Completed",
    description: "A merchant settlement was completed.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Settlement Domain",
    producer: "settlement-service",
    consumers: ["ledger-service", "merchant-service", "analytics-service", "notification-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "FOREVER", reason: "Financial record — regulatory" },
    requiredFields: ["settlementId", "merchantId", "amountMinor", "currency"],
    optionalFields: ["transactionCount", "period"],
    example: {
      settlementId: "sett_01HF...",
      merchantId: "mer_01HD...",
      amountMinor: 5000000,
      currency: "NGN",
    },
  },
  {
    eventType: "WALLET.FUNDED",
    name: "Wallet Funded",
    description: "A wallet was funded.",
    category: "FINANCIAL",
    stream: "wallets",
    priority: "HIGH",
    classification: "CONFIDENTIAL",
    owner: "Wallet Domain",
    producer: "wallet-service",
    consumers: ["ledger-service", "analytics-service", "notification-service", "rewards-service"],
    version: "v1",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Financial record" },
    requiredFields: ["walletId", "userId", "amountMinor", "currency", "source"],
    optionalFields: ["reference"],
    example: {
      walletId: "wal_01H9...",
      userId: "usr_01H7...",
      amountMinor: 100000,
      currency: "NGN",
      source: "card",
    },
  },

  // ===== Provider Events =====
  {
    eventType: "PROVIDER.UP",
    name: "Provider Up",
    description: "A provider recovered from an outage.",
    category: "PROVIDER",
    stream: "provider",
    priority: "HIGH",
    classification: "INTERNAL",
    owner: "Provider Domain",
    producer: "health-service",
    consumers: ["analytics-service", "notification-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 2, reason: "Provider ops history" },
    requiredFields: ["providerCode", "healthScore"],
    optionalFields: ["downtime"],
    example: { providerCode: "paystack", healthScore: 98 },
  },
  {
    eventType: "PROVIDER.DOWN",
    name: "Provider Down",
    description: "A provider went down.",
    category: "PROVIDER",
    stream: "provider",
    priority: "CRITICAL",
    classification: "INTERNAL",
    owner: "Provider Domain",
    producer: "health-service",
    consumers: ["routing-service", "analytics-service", "notification-service", "audit-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 2, reason: "Provider ops history" },
    requiredFields: ["providerCode", "reason"],
    optionalFields: ["affectedEndpoints"],
    example: { providerCode: "paystack", reason: "circuit_breaker_open" },
  },
  {
    eventType: "PROVIDER.DEGRADED",
    name: "Provider Degraded",
    description: "A provider is performing below threshold.",
    category: "PROVIDER",
    stream: "provider",
    priority: "HIGH",
    classification: "INTERNAL",
    owner: "Provider Domain",
    producer: "health-service",
    consumers: ["routing-service", "analytics-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 2, reason: "Provider ops history" },
    requiredFields: ["providerCode", "healthScore", "metric"],
    optionalFields: ["threshold"],
    example: { providerCode: "flutterwave", healthScore: 72, metric: "success_rate" },
  },
  {
    eventType: "WEBHOOK.RECEIVED",
    name: "Webhook Received",
    description: "An inbound webhook was received from a provider.",
    category: "PROVIDER",
    stream: "provider",
    priority: "HIGH",
    classification: "INTERNAL",
    owner: "Provider Domain",
    producer: "webhook-service",
    consumers: ["orchestrator", "audit-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 2, reason: "Webhook audit" },
    requiredFields: ["providerCode", "eventId", "eventType"],
    optionalFields: ["signatureValid", "transactionId"],
    example: { providerCode: "paystack", eventId: "evt_123", eventType: "charge.success" },
  },
  {
    eventType: "PLUGIN.UPDATED",
    name: "Plugin Updated",
    description: "A provider plugin was updated.",
    category: "PROVIDER",
    stream: "provider",
    priority: "MEDIUM",
    classification: "INTERNAL",
    owner: "Provider Domain",
    producer: "plugin-manager",
    consumers: ["analytics-service", "audit-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 2, reason: "Plugin change audit" },
    requiredFields: ["providerCode", "version", "updatedBy"],
    optionalFields: ["changes"],
    example: { providerCode: "paystack", version: "1.2.0", updatedBy: "usr_admin" },
  },

  // ===== Compliance Events =====
  {
    eventType: "KYC.SUBMITTED",
    name: "KYC Submitted",
    description: "A KYC verification was submitted.",
    category: "COMPLIANCE",
    stream: "compliance",
    priority: "HIGH",
    classification: "CONFIDENTIAL",
    owner: "Compliance Domain",
    producer: "kyc-service",
    consumers: ["analytics-service", "notification-service"],
    version: "v1",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Compliance audit" },
    requiredFields: ["userId", "tier", "documents"],
    optionalFields: ["providerCode"],
    example: { userId: "usr_01H7...", tier: 2, documents: ["passport"] },
  },
  {
    eventType: "KYC.APPROVED",
    name: "KYC Approved",
    description: "A KYC verification was approved.",
    category: "COMPLIANCE",
    stream: "compliance",
    priority: "HIGH",
    classification: "CONFIDENTIAL",
    owner: "Compliance Domain",
    producer: "kyc-service",
    consumers: ["wallet-service", "analytics-service", "notification-service"],
    version: "v1",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Compliance audit" },
    requiredFields: ["userId", "tier"],
    optionalFields: ["approvedBy", "providerCode"],
    example: { userId: "usr_01H7...", tier: 2 },
  },
  {
    eventType: "AML.FAILED",
    name: "AML Failed",
    description: "An AML screening failed.",
    category: "COMPLIANCE",
    stream: "compliance",
    priority: "CRITICAL",
    classification: "RESTRICTED",
    owner: "Compliance Domain",
    producer: "compliance-service",
    consumers: ["audit-service", "notification-service", "risk-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "FOREVER", reason: "Regulatory requirement" },
    requiredFields: ["userId", "reason", "severity"],
    optionalFields: ["matchName", "list"],
    example: { userId: "usr_01H7...", reason: "sanctions_match", severity: "HIGH" },
  },
  {
    eventType: "SANCTION.MATCH",
    name: "Sanction Match",
    description: "A sanctions list match was found.",
    category: "COMPLIANCE",
    stream: "compliance",
    priority: "CRITICAL",
    classification: "RESTRICTED",
    owner: "Compliance Domain",
    producer: "compliance-service",
    consumers: ["audit-service", "risk-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "FOREVER", reason: "Regulatory requirement" },
    requiredFields: ["entityType", "entityId", "matchName", "list"],
    optionalFields: ["score"],
    example: { entityType: "USER", entityId: "usr_01H7...", matchName: "John Doe", list: "OFAC" },
  },

  // ===== Security Events =====
  {
    eventType: "LOGIN.SUCCESS",
    name: "Login Success",
    description: "A user logged in successfully.",
    category: "SECURITY",
    stream: "security",
    priority: "MEDIUM",
    classification: "INTERNAL",
    owner: "Security Domain",
    producer: "auth-service",
    consumers: ["analytics-service", "audit-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 2, reason: "Security audit" },
    requiredFields: ["userId", "method"],
    optionalFields: ["ip", "userAgent", "deviceId"],
    example: { userId: "usr_01H7...", method: "password", ip: "102.89.0.1" },
  },
  {
    eventType: "LOGIN.FAILED",
    name: "Login Failed",
    description: "A login attempt failed.",
    category: "SECURITY",
    stream: "security",
    priority: "HIGH",
    classification: "INTERNAL",
    owner: "Security Domain",
    producer: "auth-service",
    consumers: ["risk-service", "audit-service", "analytics-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 2, reason: "Security audit" },
    requiredFields: ["identifier", "reason"],
    optionalFields: ["ip", "userAgent"],
    example: { identifier: "john@example.com", reason: "invalid_password", ip: "102.89.0.1" },
  },
  {
    eventType: "DEVICE.REGISTERED",
    name: "Device Registered",
    description: "A new device was registered.",
    category: "SECURITY",
    stream: "security",
    priority: "MEDIUM",
    classification: "INTERNAL",
    owner: "Security Domain",
    producer: "auth-service",
    consumers: ["analytics-service", "audit-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 2, reason: "Security audit" },
    requiredFields: ["userId", "deviceId", "fingerprint"],
    optionalFields: ["deviceName", "os"],
    example: { userId: "usr_01H7...", deviceId: "dev_01HB...", fingerprint: "sha256:..." },
  },
  {
    eventType: "TOKEN.REVOKED",
    name: "Token Revoked",
    description: "A session token was revoked.",
    category: "SECURITY",
    stream: "security",
    priority: "HIGH",
    classification: "RESTRICTED",
    owner: "Security Domain",
    producer: "auth-service",
    consumers: ["audit-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 2, reason: "Security audit" },
    requiredFields: ["userId", "tokenId", "reason"],
    optionalFields: ["adminId"],
    example: { userId: "usr_01H7...", tokenId: "rft_01HA...", reason: "user_logout" },
  },

  // ===== System Events =====
  {
    eventType: "FX.UPDATED",
    name: "FX Updated",
    description: "Exchange rates were updated.",
    category: "SYSTEM",
    stream: "system",
    priority: "MEDIUM",
    classification: "PUBLIC",
    owner: "FX Domain",
    producer: "fx-service",
    consumers: ["analytics-service", "wallet-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "YEARS", value: 5, reason: "FX history" },
    requiredFields: ["base", "quote", "rate", "source"],
    optionalFields: ["spreadBps"],
    example: { base: "USD", quote: "NGN", rate: 1580.5, source: "paystack" },
  },
  {
    eventType: "INVOICE.PAID",
    name: "Invoice Paid",
    description: "An invoice was paid.",
    category: "FINANCIAL",
    stream: "merchant",
    priority: "HIGH",
    classification: "CONFIDENTIAL",
    owner: "Merchant Domain",
    producer: "merchant-service",
    consumers: ["ledger-service", "analytics-service", "notification-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "FOREVER", reason: "Financial record" },
    requiredFields: ["invoiceId", "merchantId", "amountMinor"],
    optionalFields: ["customerId", "paymentMethod"],
    example: { invoiceId: "inv_01HF...", merchantId: "mer_01HD...", amountMinor: 250000 },
  },
  {
    eventType: "CHARGEBACK.OPENED",
    name: "Chargeback Opened",
    description: "A chargeback was opened by a card scheme.",
    category: "FINANCIAL",
    stream: "payments",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Payment Domain",
    producer: "payment-service",
    consumers: ["ledger-service", "risk-service", "analytics-service", "notification-service"],
    version: "v1",
    ordered: false,
    retention: { policy: "FOREVER", reason: "Financial record — disputes" },
    requiredFields: ["chargebackId", "transactionId", "amountMinor", "reason"],
    optionalFields: ["providerCode"],
    example: {
      chargebackId: "cbk_01HJ...",
      transactionId: "txn_01H8...",
      amountMinor: 100000,
      reason: "FRAUD",
    },
  },
  {
    eventType: "LEDGER.POSTED",
    name: "Ledger Posted",
    description: "A journal entry was posted to the ledger.",
    category: "FINANCIAL",
    stream: "ledger",
    priority: "CRITICAL",
    classification: "CONFIDENTIAL",
    owner: "Ledger Domain",
    producer: "ledger-service",
    consumers: ["analytics-service"],
    version: "v1",
    ordered: true,
    retention: { policy: "FOREVER", reason: "Financial record — immutable" },
    requiredFields: ["journalEntryId", "accountId", "amountMinor", "debitCredit"],
    optionalFields: ["transactionId", "pairId"],
    example: {
      journalEntryId: "jrn_01HB...",
      accountId: "lac_01HA...",
      amountMinor: 100000,
      debitCredit: "CREDIT",
    },
  },
];

// ---------------------------------------------------------------------------
// Registry helpers
// ---------------------------------------------------------------------------

export function getEventContract(eventType: string): EventContract | undefined {
  return EVENT_REGISTRY.find((e) => e.eventType === eventType);
}

export function getEventsByCategory(category: EventCategory): EventContract[] {
  return EVENT_REGISTRY.filter((e) => e.category === category);
}

export function getEventsByStream(stream: EventStream): EventContract[] {
  return EVENT_REGISTRY.filter((e) => e.stream === stream);
}

export function getEventsByProducer(producer: string): EventContract[] {
  return EVENT_REGISTRY.filter((e) => e.producer === producer);
}

export function getEventsByConsumer(consumer: string): EventContract[] {
  return EVENT_REGISTRY.filter((e) => e.consumers.includes(consumer));
}

export function getRegistryStats() {
  const byCategory = EVENT_REGISTRY.reduce(
    (acc, e) => {
      acc[e.category] = (acc[e.category] ?? 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );
  const byStream = EVENT_REGISTRY.reduce(
    (acc, e) => {
      acc[e.stream] = (acc[e.stream] ?? 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );
  const byPriority = EVENT_REGISTRY.reduce(
    (acc, e) => {
      acc[e.priority] = (acc[e.priority] ?? 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );
  const byClassification = EVENT_REGISTRY.reduce(
    (acc, e) => {
      acc[e.classification] = (acc[e.classification] ?? 0) + 1;
      return acc;
    },
    {} as Record<string, number>
  );

  return {
    totalEvents: EVENT_REGISTRY.length,
    byCategory,
    byStream,
    byPriority,
    byClassification,
    totalConsumers: new Set(EVENT_REGISTRY.flatMap((e) => e.consumers)).size,
    totalProducers: new Set(EVENT_REGISTRY.map((e) => e.producer)).size,
  };
}
