// TurboCore — Database Domain Catalog (Chapter 8)
//
// TurboCore's database is divided into 14 bounded domains. Each domain owns
// its own schema (via Prisma models) and APIs. This catalog is the single
// source of truth for "what tables exist, in which domain, and why".
//
// Used by:
//   - The admin "Database Architecture" tab to render the domain map
//   - The API layer to validate that queries stay within domain boundaries
//   - Future service extraction (each domain becomes a microservice)

export type DbDomain =
  | "identity"
  | "customers"
  | "wallets"
  | "ledger"
  | "payments"
  | "providers"
  | "capabilities"
  | "countries"
  | "merchants"
  | "compliance"
  | "risk"
  | "fx"
  | "notifications"
  | "audit"
  | "configuration"
  | "analytics"
  | "events";

export interface DomainTable {
  /** Prisma model name (or planned name). */
  model: string;
  /** Human-friendly table name. */
  name: string;
  /** What this table stores. */
  purpose: string;
  /** Whether the table exists in the current Prisma schema. */
  exists: boolean;
  /** Key columns that are indexed. */
  keyIndexes: string[];
  /** Whether this table should be partitioned by time. */
  partitioned: boolean;
  /** Whether this table uses soft-delete (status + deletedAt + deletedBy). */
  softDelete: boolean;
  /** ID prefix for public-facing references. */
  idPrefix: string;
}

export interface DomainInfo {
  id: DbDomain;
  name: string;
  description: string;
  icon: string;
  accent: string;
  order: number;
  /** The golden rule for this domain. */
  principle: string;
  tables: DomainTable[];
}

// ---------------------------------------------------------------------------
// The 14+ domains from Chapter 8
// ---------------------------------------------------------------------------

export const DOMAINS: DomainInfo[] = [
  {
    id: "identity",
    name: "Identity",
    description: "Authentication, sessions, devices, passkeys, OAuth, MFA.",
    icon: "ShieldCheck",
    accent: "violet",
    order: 1,
    principle: "Identity is the gate. Every action traces to a verified identity.",
    tables: [
      {
        model: "User",
        name: "users",
        purpose: "Core user record — email, phone, role, KYC tier.",
        exists: true,
        keyIndexes: ["email", "phone", "role"],
        partitioned: false,
        softDelete: true,
        idPrefix: "usr",
      },
      {
        model: "Session",
        name: "sessions",
        purpose: "Active login sessions with device + IP tracking.",
        exists: true,
        keyIndexes: ["userId", "expiresAt"],
        partitioned: false,
        softDelete: false,
        idPrefix: "ses",
      },
      {
        model: "Device",
        name: "devices",
        purpose: "Trusted device fingerprints.",
        exists: true,
        keyIndexes: ["userId", "fingerprint"],
        partitioned: false,
        softDelete: true,
        idPrefix: "dev",
      },
      {
        model: "Passkey",
        name: "passkeys",
        purpose: "WebAuthn credential registrations.",
        exists: true,
        keyIndexes: ["userId"],
        partitioned: false,
        softDelete: true,
        idPrefix: "psk",
      },
      {
        model: "MfaSecret",
        name: "mfa_secrets",
        purpose: "TOTP MFA secrets (encrypted).",
        exists: true,
        keyIndexes: ["userId"],
        partitioned: false,
        softDelete: true,
        idPrefix: "mfa",
      },
      {
        model: "OAuthAccount",
        name: "oauth_accounts",
        purpose: "Linked social accounts (Google).",
        exists: true,
        keyIndexes: ["provider", "providerAccountId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "oau",
      },
      {
        model: "RefreshToken",
        name: "refresh_tokens",
        purpose: "JWT refresh tokens (hashed).",
        exists: true,
        keyIndexes: ["userId", "tokenHash"],
        partitioned: false,
        softDelete: false,
        idPrefix: "rft",
      },
      {
        model: "TeamMember",
        name: "team_members",
        purpose: "Admin team members with roles.",
        exists: true,
        keyIndexes: ["userId", "role"],
        partitioned: false,
        softDelete: true,
        idPrefix: "tm",
      },
    ],
  },
  {
    id: "customers",
    name: "Customers",
    description: "Customer profiles, preferences, addresses, documents, consents.",
    icon: "Users",
    accent: "blue",
    order: 2,
    principle: "One table per concern. Profile ≠ Preferences ≠ Address.",
    tables: [
      {
        model: "User",
        name: "customers",
        purpose: "Core customer record (reuses User model).",
        exists: true,
        keyIndexes: ["email", "phone", "kycTier"],
        partitioned: false,
        softDelete: true,
        idPrefix: "cus",
      },
      {
        model: "CustomerProfile",
        name: "customer_profiles",
        purpose: "Extended profile — DOB, occupation, nationality.",
        exists: false,
        keyIndexes: ["userId"],
        partitioned: false,
        softDelete: true,
        idPrefix: "cpr",
      },
      {
        model: "CustomerPreference",
        name: "customer_preferences",
        purpose: "User preferences — language, theme, notifications.",
        exists: false,
        keyIndexes: ["userId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cpf",
      },
      {
        model: "CustomerAddress",
        name: "customer_addresses",
        purpose: "Physical addresses — billing, shipping, residential.",
        exists: false,
        keyIndexes: ["userId", "type"],
        partitioned: false,
        softDelete: true,
        idPrefix: "cad",
      },
      {
        model: "CommunicationPreference",
        name: "communication_consents",
        purpose: "Marketing + communication opt-ins (GDPR).",
        exists: true,
        keyIndexes: ["userId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cco",
      },
      {
        model: "TransferTemplate",
        name: "transfer_templates",
        purpose: "Saved transfer beneficiaries.",
        exists: true,
        keyIndexes: ["userId"],
        partitioned: false,
        softDelete: true,
        idPrefix: "tpl",
      },
      {
        model: "Beneficiary",
        name: "beneficiaries",
        purpose: "Saved bank/wallet beneficiaries.",
        exists: true,
        keyIndexes: ["userId", "type"],
        partitioned: false,
        softDelete: true,
        idPrefix: "ben",
      },
      {
        model: "SpendingBudget",
        name: "spending_budgets",
        purpose: "Per-category spending limits.",
        exists: true,
        keyIndexes: ["userId", "category"],
        partitioned: false,
        softDelete: false,
        idPrefix: "bud",
      },
      {
        model: "UserBadge",
        name: "user_badges",
        purpose: "Gamification badges.",
        exists: true,
        keyIndexes: ["userId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "bdg",
      },
    ],
  },
  {
    id: "wallets",
    name: "Wallets",
    description: "Stored-value accounts. Wallets do NOT own accounting — Ledger does.",
    icon: "Wallet",
    accent: "amber",
    order: 3,
    principle: "Wallets do not own accounting. Ledger does.",
    tables: [
      {
        model: "Wallet",
        name: "wallets",
        purpose: "Primary wallet — balance in kobo.",
        exists: true,
        keyIndexes: ["userId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "wal",
      },
      {
        model: "CurrencyWallet",
        name: "currency_wallets",
        purpose: "Multi-currency wallet balances.",
        exists: true,
        keyIndexes: ["userId", "currency"],
        partitioned: false,
        softDelete: true,
        idPrefix: "cwh",
      },
      {
        model: "SavingsProduct",
        name: "savings_products",
        purpose: "Savings product definitions.",
        exists: true,
        keyIndexes: ["status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "sav",
      },
      {
        model: "SavingsTransaction",
        name: "savings_transactions",
        purpose: "Savings deposit/withdrawal records.",
        exists: true,
        keyIndexes: ["userId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "str",
      },
      {
        model: "AutoSaveRule",
        name: "auto_save_rules",
        purpose: "Scheduled auto-save rules.",
        exists: true,
        keyIndexes: ["userId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "asr",
      },
      {
        model: "SavingsGoal",
        name: "savings_goals",
        purpose: "Goal-based savings targets.",
        exists: true,
        keyIndexes: ["userId"],
        partitioned: false,
        softDelete: true,
        idPrefix: "sgl",
      },
      {
        model: "InvestmentProduct",
        name: "investment_products",
        purpose: "Investment product definitions.",
        exists: true,
        keyIndexes: ["status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "inv",
      },
      {
        model: "UserInvestment",
        name: "user_investments",
        purpose: "User investment holdings.",
        exists: true,
        keyIndexes: ["userId", "productId"],
        partitioned: false,
        softDelete: true,
        idPrefix: "uiv",
      },
      {
        model: "VirtualCard",
        name: "virtual_cards",
        purpose: "Virtual card definitions.",
        exists: true,
        keyIndexes: ["userId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "vcd",
      },
      {
        model: "VirtualCardTransaction",
        name: "virtual_card_transactions",
        purpose: "Virtual card transaction history.",
        exists: true,
        keyIndexes: ["cardId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "vct",
      },
    ],
  },
  {
    id: "ledger",
    name: "Ledger",
    description:
      "The most important domain. Immutable journal entries, chart of accounts, reconciliation.",
    icon: "BookOpen",
    accent: "emerald",
    order: 4,
    principle: "Never delete financial data. Use immutable journal entries.",
    tables: [
      {
        model: "LedgerAccount",
        name: "ledger_accounts",
        purpose: "Chart of accounts — asset/liability/revenue/expense.",
        exists: true,
        keyIndexes: ["code", "type", "subType", "ownerId"],
        partitioned: false,
        softDelete: true,
        idPrefix: "lac",
      },
      {
        model: "JournalEntry",
        name: "journal_entries",
        purpose: "Immutable double-entry journal lines.",
        exists: true,
        keyIndexes: ["accountId", "transactionId", "pairId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "jrn",
      },
      {
        model: "BalanceSnapshot",
        name: "balance_snapshots",
        purpose: "Point-in-time balance snapshots for reconciliation.",
        exists: true,
        keyIndexes: ["accountId", "snapshotDate"],
        partitioned: true,
        softDelete: false,
        idPrefix: "bsn",
      },
      {
        model: "AccountingPeriod",
        name: "accounting_periods",
        purpose: "Closing periods — daily, monthly, fiscal year.",
        exists: true,
        keyIndexes: ["type", "startDate", "status"],
        partitioned: false,
        softDelete: false,
        idPrefix: "acp",
      },
      {
        model: "ReconciliationRun",
        name: "reconciliation_runs",
        purpose: "Reconciliation execution records.",
        exists: true,
        keyIndexes: ["providerCode", "periodStart"],
        partitioned: false,
        softDelete: false,
        idPrefix: "rec",
      },
      {
        model: "LedgerEntry",
        name: "ledger_entries",
        purpose: "Legacy ledger entries (pre-FLE).",
        exists: true,
        keyIndexes: ["walletId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "led",
      },
      {
        model: "CurrencyLedgerEntry",
        name: "currency_ledger_entries",
        purpose: "Multi-currency ledger entries.",
        exists: true,
        keyIndexes: ["currencyWalletId", "userId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "cle",
      },
      {
        model: "JournalBatch",
        name: "journal_batches",
        purpose: "Batched journal postings for bulk operations.",
        exists: false,
        keyIndexes: ["status", "createdAt"],
        partitioned: false,
        softDelete: false,
        idPrefix: "jbt",
      },
    ],
  },
  {
    id: "payments",
    name: "Payments",
    description:
      "Payments, attempts, methods, events, refunds, chargebacks. Normalized payment history.",
    icon: "CreditCard",
    accent: "rose",
    order: 5,
    principle: "Payment history is normalized. One table per concern.",
    tables: [
      {
        model: "Transaction",
        name: "transactions",
        purpose: "Core transaction record — the golden record.",
        exists: true,
        keyIndexes: ["reference", "userId", "status", "providerCode", "createdAt"],
        partitioned: true,
        softDelete: true,
        idPrefix: "txn",
      },
      {
        model: "TransactionEvent",
        name: "transaction_events",
        purpose: "Immutable append-only event log per transaction.",
        exists: true,
        keyIndexes: ["transactionId", "eventType", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "tev",
      },
      {
        model: "PaymentFlowLog",
        name: "payment_flow_logs",
        purpose: "Orchestrator step traces — HOLD/CONFIRM/REVERSE.",
        exists: true,
        keyIndexes: ["transactionId", "step", "at"],
        partitioned: true,
        softDelete: false,
        idPrefix: "pfl",
      },
      {
        model: "PaymentRoutingDecision",
        name: "payment_routing_decisions",
        purpose: "Routing decisions with scores + alternatives.",
        exists: true,
        keyIndexes: ["transactionId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "prd",
      },
      {
        model: "VirtualAccount",
        name: "virtual_accounts",
        purpose: "Generated virtual account numbers.",
        exists: true,
        keyIndexes: ["userId", "accountNumber"],
        partitioned: false,
        softDelete: true,
        idPrefix: "vac",
      },
      {
        model: "BillPayment",
        name: "bill_payments",
        purpose: "Bill payment records.",
        exists: true,
        keyIndexes: ["userId", "billerCode"],
        partitioned: false,
        softDelete: false,
        idPrefix: "blp",
      },
      {
        model: "AirtimeDataPurchase",
        name: "airtime_data_purchases",
        purpose: "Airtime/data purchase records.",
        exists: true,
        keyIndexes: ["userId", "phone"],
        partitioned: false,
        softDelete: false,
        idPrefix: "adp",
      },
      {
        model: "Refund",
        name: "refunds",
        purpose: "Refund records with original payment link.",
        exists: false,
        keyIndexes: ["transactionId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "rfd",
      },
      {
        model: "Chargeback",
        name: "chargebacks",
        purpose: "Card scheme chargeback records.",
        exists: false,
        keyIndexes: ["transactionId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "cbk",
      },
      {
        model: "PaymentAttempt",
        name: "payment_attempts",
        purpose: "Per-attempt records for retried payments.",
        exists: false,
        keyIndexes: ["transactionId", "status"],
        partitioned: true,
        softDelete: false,
        idPrefix: "pat",
      },
      {
        model: "PaymentMethod",
        name: "payment_methods",
        purpose: "Saved payment methods (tokens, bank accounts).",
        exists: false,
        keyIndexes: ["userId", "type"],
        partitioned: false,
        softDelete: true,
        idPrefix: "pmh",
      },
      {
        model: "ScheduledPayment",
        name: "scheduled_payments",
        purpose: "Future-dated scheduled payments.",
        exists: true,
        keyIndexes: ["userId", "status", "nextRunAt"],
        partitioned: false,
        softDelete: true,
        idPrefix: "sch",
      },
      {
        model: "Mandate",
        name: "mandates",
        purpose: "Direct debit mandates.",
        exists: true,
        keyIndexes: ["userId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "mnd",
      },
      {
        model: "Subscription",
        name: "subscriptions",
        purpose: "Active subscriptions.",
        exists: true,
        keyIndexes: ["userId", "planId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "sub",
      },
      {
        model: "SubscriptionPlan",
        name: "subscription_plans",
        purpose: "Subscription plan definitions.",
        exists: true,
        keyIndexes: ["status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "spl",
      },
      {
        model: "Dispute",
        name: "disputes",
        purpose: "Payment dispute records.",
        exists: true,
        keyIndexes: ["transactionId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "dsp",
      },
      {
        model: "DisputeMessage",
        name: "dispute_messages",
        purpose: "Dispute communication threads.",
        exists: true,
        keyIndexes: ["disputeId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "dsm",
      },
    ],
  },
  {
    id: "providers",
    name: "Providers",
    description: "Everything about providers stays isolated. Configs, credentials, health, routes.",
    icon: "Server",
    accent: "cyan",
    order: 6,
    principle: "Everything about providers stays isolated.",
    tables: [
      {
        model: "ProviderConfig",
        name: "provider_configs",
        purpose: "Provider configuration — code, name, status.",
        exists: true,
        keyIndexes: ["code", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "prv",
      },
      {
        model: "ProviderCredentialVersion",
        name: "provider_credentials",
        purpose: "Versioned provider credentials (encrypted).",
        exists: true,
        keyIndexes: ["providerCode", "version"],
        partitioned: false,
        softDelete: false,
        idPrefix: "pcr",
      },
      {
        model: "ProviderRoute",
        name: "provider_routes",
        purpose: "Routing rules per contract/country.",
        exists: true,
        keyIndexes: ["contract", "country", "priority"],
        partitioned: false,
        softDelete: true,
        idPrefix: "prt",
      },
      {
        model: "ProviderHealthCheck",
        name: "provider_health_checks",
        purpose: "Health check results over time.",
        exists: true,
        keyIndexes: ["providerCode", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "phc",
      },
      {
        model: "ProviderCapability",
        name: "provider_capabilities",
        purpose: "Per-provider capability matrix (contract × country × currency).",
        exists: true,
        keyIndexes: ["contract", "country", "currency", "enabled"],
        partitioned: false,
        softDelete: true,
        idPrefix: "pcb",
      },
      {
        model: "WebhookEndpoint",
        name: "webhook_endpoints",
        purpose: "Provider webhook endpoint configs.",
        exists: true,
        keyIndexes: ["providerCode"],
        partitioned: false,
        softDelete: true,
        idPrefix: "whe",
      },
      {
        model: "ProviderIncident",
        name: "provider_incidents",
        purpose: "Provider outage/incident records.",
        exists: false,
        keyIndexes: ["providerCode", "status", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "pin",
      },
      {
        model: "ProviderLatency",
        name: "provider_latency",
        purpose: "Per-endpoint latency metrics.",
        exists: false,
        keyIndexes: ["providerCode", "endpoint", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "plt",
      },
    ],
  },
  {
    id: "capabilities",
    name: "Capabilities (GCR)",
    description:
      "Capability groups, dependencies, versions, country/provider support. Powers Chapter 7.",
    icon: "Network",
    accent: "indigo",
    order: 7,
    principle: "TurboCore routes to Capabilities, never to providers.",
    tables: [
      {
        model: "CapabilityGroup",
        name: "capability_groups",
        purpose: "22 capability groups (Collections, Disbursements, etc.).",
        exists: false,
        keyIndexes: ["id", "order"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cgp",
      },
      {
        model: "Capability",
        name: "capabilities",
        purpose: "205 capabilities with metadata + documentation.",
        exists: false,
        keyIndexes: ["groupId", "status", "direction"],
        partitioned: false,
        softDelete: true,
        idPrefix: "cap",
      },
      {
        model: "CapabilityDependency",
        name: "capability_dependencies",
        purpose: "Knowledge graph edges (REQUIRES/RECOMMENDS).",
        exists: false,
        keyIndexes: ["capabilityId", "dependencyId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cdp",
      },
      {
        model: "CapabilityVersion",
        name: "capability_versions",
        purpose: "Versioned capability definitions.",
        exists: false,
        keyIndexes: ["capabilityId", "version"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cvr",
      },
      {
        model: "CapabilityCountrySupport",
        name: "capability_country_support",
        purpose: "Per-country support levels (FULL/LIMITED/BETA).",
        exists: false,
        keyIndexes: ["capabilityId", "country"],
        partitioned: false,
        softDelete: false,
        idPrefix: "ccs",
      },
      {
        model: "CapabilityProviderSupport",
        name: "capability_provider_support",
        purpose: "Per-provider maturity per capability.",
        exists: false,
        keyIndexes: ["capabilityId", "providerCode"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cps",
      },
      {
        model: "CapabilityFlag",
        name: "capability_flags",
        purpose: "Runtime feature flags per capability/scope/target.",
        exists: false,
        keyIndexes: ["capabilityId", "scope", "target"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cfg",
      },
    ],
  },
  {
    id: "countries",
    name: "Countries",
    description:
      "Countries, currencies, capabilities, providers, limits, KYC, tax, settlement per country.",
    icon: "Globe",
    accent: "green",
    order: 8,
    principle: "Nothing should be hardcoded. Country behaviour is configuration.",
    tables: [
      {
        model: "CountryConfig",
        name: "country_configs",
        purpose: "Per-country configuration — currency, dial code, KYC.",
        exists: true,
        keyIndexes: ["code", "enabled"],
        partitioned: false,
        softDelete: true,
        idPrefix: "ctry",
      },
      {
        model: "Currency",
        name: "currencies",
        purpose: "Currency definitions — code, symbol, decimals.",
        exists: false,
        keyIndexes: ["code"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cur",
      },
      {
        model: "CountryCapability",
        name: "country_capabilities",
        purpose: "Which capabilities are enabled per country.",
        exists: false,
        keyIndexes: ["country", "capabilityId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "ccc",
      },
      {
        model: "CountryProvider",
        name: "country_providers",
        purpose: "Preferred provider ordering per country.",
        exists: false,
        keyIndexes: ["country", "providerCode"],
        partitioned: false,
        softDelete: false,
        idPrefix: "ccp",
      },
      {
        model: "CountryLimit",
        name: "country_limits",
        purpose: "Per-country transaction limits.",
        exists: false,
        keyIndexes: ["country", "tier"],
        partitioned: false,
        softDelete: false,
        idPrefix: "clm",
      },
      {
        model: "CountryKyc",
        name: "country_kyc",
        purpose: "Per-country KYC requirements.",
        exists: false,
        keyIndexes: ["country"],
        partitioned: false,
        softDelete: false,
        idPrefix: "ckc",
      },
      {
        model: "CountryTax",
        name: "country_tax",
        purpose: "Per-country tax rules.",
        exists: false,
        keyIndexes: ["country"],
        partitioned: false,
        softDelete: false,
        idPrefix: "ctx",
      },
      {
        model: "CountrySettlement",
        name: "country_settlement",
        purpose: "Per-country settlement rules.",
        exists: false,
        keyIndexes: ["country"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cst",
      },
    ],
  },
  {
    id: "merchants",
    name: "Merchants",
    description: "Merchant accounts, wallets, fees, settlements, team, webhooks, branding.",
    icon: "Store",
    accent: "orange",
    order: 9,
    principle: "Merchants are first-class citizens with their own wallet + settlement cycle.",
    tables: [
      {
        model: "Merchant",
        name: "merchants",
        purpose: "Merchant master record.",
        exists: true,
        keyIndexes: ["email", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "mer",
      },
      {
        model: "MerchantApiKey",
        name: "merchant_api_keys",
        purpose: "Merchant API keys (hashed).",
        exists: true,
        keyIndexes: ["merchantId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "mak",
      },
      {
        model: "PaymentLink",
        name: "payment_links",
        purpose: "Merchant payment links.",
        exists: true,
        keyIndexes: ["merchantId", "slug", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "plk",
      },
      {
        model: "PaymentLinkPayment",
        name: "payment_link_payments",
        purpose: "Payments received via payment links.",
        exists: true,
        keyIndexes: ["paymentLinkId", "status"],
        partitioned: true,
        softDelete: false,
        idPrefix: "plp",
      },
      {
        model: "MarketplaceMerchant",
        name: "marketplace_merchants",
        purpose: "Marketplace seller profiles.",
        exists: true,
        keyIndexes: ["merchantId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "mkm",
      },
      {
        model: "MerchantReview",
        name: "merchant_reviews",
        purpose: "Customer reviews of marketplace merchants.",
        exists: true,
        keyIndexes: ["merchantId", "userId"],
        partitioned: false,
        softDelete: true,
        idPrefix: "mrv",
      },
      {
        model: "MerchantFee",
        name: "merchant_fees",
        purpose: "Per-merchant fee schedules.",
        exists: false,
        keyIndexes: ["merchantId", "contract"],
        partitioned: false,
        softDelete: false,
        idPrefix: "mfe",
      },
      {
        model: "MerchantWebhook",
        name: "merchant_webhooks",
        purpose: "Merchant webhook endpoint configs.",
        exists: false,
        keyIndexes: ["merchantId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "mwh",
      },
      {
        model: "MerchantBranding",
        name: "merchant_branding",
        purpose: "Merchant branding — logo, colors, domain.",
        exists: false,
        keyIndexes: ["merchantId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "mbr",
      },
    ],
  },
  {
    id: "compliance",
    name: "Compliance",
    description: "KYC, KYB, identity documents, sanctions, PEP, AML screening.",
    icon: "Scale",
    accent: "fuchsia",
    order: 10,
    principle: "Every verification has an audit trail. Hits require analyst review.",
    tables: [
      {
        model: "KycVerification",
        name: "kyc_verifications",
        purpose: "KYC verification requests + results.",
        exists: true,
        keyIndexes: ["userId", "status"],
        partitioned: false,
        softDelete: false,
        idPrefix: "kyc",
      },
      {
        model: "KycTierLimit",
        name: "kyc_tier_limits",
        purpose: "Per-tier transaction limits.",
        exists: true,
        keyIndexes: ["tier"],
        partitioned: false,
        softDelete: false,
        idPrefix: "ktl",
      },
      {
        model: "SanctionsEntry",
        name: "sanctions_entries",
        purpose: "Sanctions list entries (OFAC, UN).",
        exists: true,
        keyIndexes: ["name", "type"],
        partitioned: false,
        softDelete: false,
        idPrefix: "sne",
      },
      {
        model: "ScreeningResult",
        name: "screening_results",
        purpose: "Screening results per entity.",
        exists: true,
        keyIndexes: ["entityType", "entityId", "status"],
        partitioned: false,
        softDelete: false,
        idPrefix: "scr",
      },
      {
        model: "ComplianceCase",
        name: "compliance_cases",
        purpose: "Cases for analyst review.",
        exists: true,
        keyIndexes: ["status", "assignedTo"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cmp",
      },
      {
        model: "AmlFlag",
        name: "aml_flags",
        purpose: "AML risk flags per user/transaction.",
        exists: true,
        keyIndexes: ["userId", "severity"],
        partitioned: false,
        softDelete: false,
        idPrefix: "aml",
      },
      {
        model: "KybRequest",
        name: "kyb_requests",
        purpose: "Know-your-business verification requests.",
        exists: false,
        keyIndexes: ["merchantId", "status"],
        partitioned: false,
        softDelete: false,
        idPrefix: "kyb",
      },
      {
        model: "IdentityDocument",
        name: "identity_documents",
        purpose: "Customer identity documents (encrypted refs).",
        exists: false,
        keyIndexes: ["userId", "type"],
        partitioned: false,
        softDelete: true,
        idPrefix: "idd",
      },
      {
        model: "PepCheck",
        name: "pep_checks",
        purpose: "Politically-exposed-person check results.",
        exists: false,
        keyIndexes: ["userId", "status"],
        partitioned: false,
        softDelete: false,
        idPrefix: "pep",
      },
    ],
  },
  {
    id: "risk",
    name: "Risk",
    description: "Risk scores, rules, events, device fingerprints, velocity, fraud alerts.",
    icon: "ShieldAlert",
    accent: "red",
    order: 11,
    principle: "Risk rules are hot-reloadable. Every transaction gets scored.",
    tables: [
      {
        model: "RiskScore",
        name: "risk_scores",
        purpose: "Per-transaction/user risk scores.",
        exists: false,
        keyIndexes: ["entityType", "entityId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "rsk",
      },
      {
        model: "RiskRule",
        name: "risk_rules",
        purpose: "Configurable risk rules.",
        exists: false,
        keyIndexes: ["status", "priority"],
        partitioned: false,
        softDelete: true,
        idPrefix: "rrl",
      },
      {
        model: "RiskEvent",
        name: "risk_events",
        purpose: "Risk engine evaluation events.",
        exists: false,
        keyIndexes: ["entityType", "entityId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "rev",
      },
      {
        model: "Device",
        name: "device_fingerprints",
        purpose: "Device fingerprint store (reuses Device model).",
        exists: true,
        keyIndexes: ["fingerprint", "userId"],
        partitioned: false,
        softDelete: true,
        idPrefix: "dev",
      },
      {
        model: "VelocityLimit",
        name: "velocity_limits",
        purpose: "Per-user velocity limits (count + amount per window).",
        exists: false,
        keyIndexes: ["userId", "window"],
        partitioned: false,
        softDelete: false,
        idPrefix: "vel",
      },
      {
        model: "FraudAlert",
        name: "fraud_alerts",
        purpose: "Fraud alert records for analyst review.",
        exists: false,
        keyIndexes: ["userId", "status", "severity"],
        partitioned: false,
        softDelete: true,
        idPrefix: "fra",
      },
    ],
  },
  {
    id: "fx",
    name: "FX",
    description: "Exchange rates, quotes, transactions, currency pairs, spread configuration.",
    icon: "ArrowLeftRight",
    accent: "teal",
    order: 12,
    principle: "Rates are cached for 60 seconds. Quotes are locked for 5 minutes.",
    tables: [
      {
        model: "FxRateSnapshot",
        name: "fx_rate_snapshots",
        purpose: "Exchange rate snapshots over time.",
        exists: true,
        keyIndexes: ["base", "quote", "fetchedAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "fxr",
      },
      {
        model: "FxConfig",
        name: "fx_configs",
        purpose: "Per-pair spread + markup configuration.",
        exists: true,
        keyIndexes: ["base", "quote"],
        partitioned: false,
        softDelete: false,
        idPrefix: "fxc",
      },
      {
        model: "FxQuote",
        name: "fx_quotes",
        purpose: "Locked-in FX quotes with expiry.",
        exists: false,
        keyIndexes: ["base", "quote", "status", "expiresAt"],
        partitioned: false,
        softDelete: false,
        idPrefix: "fxq",
      },
      {
        model: "FxTransaction",
        name: "fx_transactions",
        purpose: "Executed FX conversion records.",
        exists: false,
        keyIndexes: ["quoteId", "userId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "fxt",
      },
      {
        model: "CurrencyPair",
        name: "currency_pairs",
        purpose: "Tradable currency pair definitions.",
        exists: false,
        keyIndexes: ["base", "quote", "status"],
        partitioned: false,
        softDelete: false,
        idPrefix: "fxp",
      },
    ],
  },
  {
    id: "notifications",
    name: "Notifications",
    description: "Notifications, templates, delivery logs, preferences.",
    icon: "Bell",
    accent: "sky",
    order: 13,
    principle: "Templates are versioned. Delivery is idempotent.",
    tables: [
      {
        model: "InAppNotification",
        name: "in_app_notifications",
        purpose: "In-app notification messages.",
        exists: true,
        keyIndexes: ["userId", "status", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "not",
      },
      {
        model: "CommunicationPreference",
        name: "notification_preferences",
        purpose: "User notification preferences (reuses model).",
        exists: true,
        keyIndexes: ["userId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "npr",
      },
      {
        model: "SupportTicket",
        name: "support_tickets",
        purpose: "Customer support tickets.",
        exists: true,
        keyIndexes: ["userId", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "tkt",
      },
      {
        model: "NotificationTemplate",
        name: "notification_templates",
        purpose: "Versioned notification templates.",
        exists: false,
        keyIndexes: ["channel", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "ntm",
      },
      {
        model: "DeliveryLog",
        name: "delivery_logs",
        purpose: "Per-message delivery logs.",
        exists: false,
        keyIndexes: ["notificationId", "channel", "status"],
        partitioned: true,
        softDelete: false,
        idPrefix: "dlg",
      },
    ],
  },
  {
    id: "audit",
    name: "Audit",
    description: "Every change. Every action. Immutable where appropriate.",
    icon: "ScrollText",
    accent: "slate",
    order: 14,
    principle: "Every change. Every action. Immutable where appropriate.",
    tables: [
      {
        model: "AuditLog",
        name: "audit_logs",
        purpose: "Core audit log — every action.",
        exists: true,
        keyIndexes: ["userId", "action", "category", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "aud",
      },
      {
        model: "ConfigVersion",
        name: "config_versions",
        purpose: "Configuration change history with snapshots.",
        exists: true,
        keyIndexes: ["scope", "version"],
        partitioned: false,
        softDelete: false,
        idPrefix: "cfv",
      },
      {
        model: "ApiAccessLog",
        name: "api_access_logs",
        purpose: "API request logs — method, path, status, latency.",
        exists: false,
        keyIndexes: ["userId", "method", "path", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "aal",
      },
      {
        model: "AdminAction",
        name: "admin_actions",
        purpose: "Admin portal actions with before/after diff.",
        exists: false,
        keyIndexes: ["adminId", "action", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "adm",
      },
    ],
  },
  {
    id: "configuration",
    name: "Configuration",
    description:
      "Feature flags, system settings, country/provider config, routing rules, fees. No deployments for config changes.",
    icon: "Settings",
    accent: "purple",
    order: 15,
    principle: "No deployments for configuration changes. Just update configuration.",
    tables: [
      {
        model: "FeatureFlag",
        name: "feature_flags",
        purpose: "Global feature flags.",
        exists: true,
        keyIndexes: ["key", "enabled"],
        partitioned: false,
        softDelete: false,
        idPrefix: "flg",
      },
      {
        model: "FeatureFlagOverride",
        name: "feature_flag_overrides",
        purpose: "Per-user/country/tier flag overrides.",
        exists: true,
        keyIndexes: ["flagKey", "targetType", "targetId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "ffo",
      },
      {
        model: "ProviderConfig",
        name: "provider_configuration",
        purpose: "Provider configuration (reuses model).",
        exists: true,
        keyIndexes: ["code", "status"],
        partitioned: false,
        softDelete: true,
        idPrefix: "prv",
      },
      {
        model: "ProviderRoute",
        name: "routing_rules",
        purpose: "Routing rules (reuses model).",
        exists: true,
        keyIndexes: ["contract", "country"],
        partitioned: false,
        softDelete: true,
        idPrefix: "rru",
      },
      {
        model: "SystemSetting",
        name: "system_settings",
        purpose: "Global system settings (key-value).",
        exists: false,
        keyIndexes: ["key"],
        partitioned: false,
        softDelete: false,
        idPrefix: "sys",
      },
      {
        model: "FeeConfig",
        name: "fee_configuration",
        purpose: "Per-capability fee schedules.",
        exists: false,
        keyIndexes: ["capabilityId", "country"],
        partitioned: false,
        softDelete: false,
        idPrefix: "fee",
      },
      {
        model: "RiskConfig",
        name: "risk_configuration",
        purpose: "Risk engine configuration.",
        exists: false,
        keyIndexes: ["ruleId"],
        partitioned: false,
        softDelete: false,
        idPrefix: "rcf",
      },
    ],
  },
  {
    id: "analytics",
    name: "Analytics",
    description: "Pre-computed metrics for dashboards. Never query live transactional tables.",
    icon: "BarChart3",
    accent: "lime",
    order: 16,
    principle: "Never query live transactional tables for dashboards. Use event projections.",
    tables: [
      {
        model: "DailyMetric",
        name: "daily_metrics",
        purpose: "Daily aggregated metrics — volume, count, revenue.",
        exists: false,
        keyIndexes: ["date", "metric"],
        partitioned: true,
        softDelete: false,
        idPrefix: "dmt",
      },
      {
        model: "ProviderMetric",
        name: "provider_metrics",
        purpose: "Per-provider daily metrics.",
        exists: false,
        keyIndexes: ["providerCode", "date"],
        partitioned: true,
        softDelete: false,
        idPrefix: "pmt",
      },
      {
        model: "MerchantMetric",
        name: "merchant_metrics",
        purpose: "Per-merchant daily metrics.",
        exists: false,
        keyIndexes: ["merchantId", "date"],
        partitioned: true,
        softDelete: false,
        idPrefix: "mmt",
      },
      {
        model: "CountryMetric",
        name: "country_metrics",
        purpose: "Per-country daily metrics.",
        exists: false,
        keyIndexes: ["country", "date"],
        partitioned: true,
        softDelete: false,
        idPrefix: "cmt",
      },
      {
        model: "RevenueMetric",
        name: "revenue_metrics",
        purpose: "Revenue breakdown by source.",
        exists: false,
        keyIndexes: ["date", "source"],
        partitioned: true,
        softDelete: false,
        idPrefix: "rvm",
      },
    ],
  },
  {
    id: "events",
    name: "Event Store",
    description: "Every important event stored. Supports replay and debugging. CQRS write model.",
    icon: "Zap",
    accent: "yellow",
    order: 17,
    principle: "Every important event should be stored. Supports replay and debugging.",
    tables: [
      {
        model: "OutboxEvent",
        name: "outbox_events",
        purpose: "Transactional outbox for reliable event publishing.",
        exists: true,
        keyIndexes: ["status", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "obx",
      },
      {
        model: "WebhookEvent",
        name: "webhook_events",
        purpose: "Inbound webhook events (idempotent).",
        exists: true,
        keyIndexes: ["providerCode", "eventId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "whe",
      },
      {
        model: "TransactionEvent",
        name: "transaction_events_store",
        purpose: "Append-only transaction event log (reuses model).",
        exists: true,
        keyIndexes: ["transactionId", "eventType"],
        partitioned: true,
        softDelete: false,
        idPrefix: "tev",
      },
      {
        model: "EventStore",
        name: "event_store",
        purpose: "Universal event store — PAYMENT.CREATED, KYC.APPROVED, etc.",
        exists: false,
        keyIndexes: ["eventType", "aggregateType", "aggregateId", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "evt",
      },
      {
        model: "AsyncTask",
        name: "async_tasks",
        purpose: "Background task queue.",
        exists: true,
        keyIndexes: ["status", "createdAt"],
        partitioned: true,
        softDelete: false,
        idPrefix: "atk",
      },
      {
        model: "CronLock",
        name: "cron_locks",
        purpose: "Distributed cron locks.",
        exists: true,
        keyIndexes: ["name", "status"],
        partitioned: false,
        softDelete: false,
        idPrefix: "crl",
      },
      {
        model: "IdempotencyRecord",
        name: "idempotency_records",
        purpose: "Idempotency key store.",
        exists: true,
        keyIndexes: ["key", "expiresAt"],
        partitioned: false,
        softDelete: false,
        idPrefix: "idm",
      },
    ],
  },
];

// ---------------------------------------------------------------------------
// Derived helpers
// ---------------------------------------------------------------------------

export function getDomain(id: DbDomain): DomainInfo | undefined {
  return DOMAINS.find((d) => d.id === id);
}

export function getAllTables(): DomainTable[] {
  return DOMAINS.flatMap((d) => d.tables);
}

export function getTableStats() {
  const all = getAllTables();
  return {
    totalDomains: DOMAINS.length,
    totalTables: all.length,
    existingTables: all.filter((t) => t.exists).length,
    plannedTables: all.filter((t) => !t.exists).length,
    partitionedTables: all.filter((t) => t.partitioned).length,
    softDeleteTables: all.filter((t) => t.softDelete).length,
    tablesByDomain: DOMAINS.map((d) => ({
      domain: d.id,
      name: d.name,
      total: d.tables.length,
      existing: d.tables.filter((t) => t.exists).length,
      planned: d.tables.filter((t) => !t.exists).length,
    })),
  };
}

// ---------------------------------------------------------------------------
// Canonical relationships (Chapter 8)
// ---------------------------------------------------------------------------

export interface Relationship {
  from: string;
  to: string;
  type: "one-to-one" | "one-to-many" | "many-to-many" | "many-to-one";
  description: string;
}

export const CANONICAL_RELATIONSHIPS: Relationship[] = [
  {
    from: "Customer",
    to: "Wallet",
    type: "one-to-many",
    description: "A customer owns one or more wallets.",
  },
  {
    from: "Wallet",
    to: "LedgerAccount",
    type: "one-to-one",
    description: "Each wallet maps to exactly one ledger account.",
  },
  {
    from: "LedgerAccount",
    to: "JournalEntry",
    type: "one-to-many",
    description: "A ledger account has many journal entries.",
  },
  {
    from: "Payment",
    to: "Provider",
    type: "many-to-one",
    description: "A payment is processed by one provider.",
  },
  {
    from: "Payment",
    to: "Settlement",
    type: "many-to-one",
    description: "Payments are grouped into settlements.",
  },
  {
    from: "Settlement",
    to: "Reconciliation",
    type: "one-to-many",
    description: "A settlement has reconciliation runs.",
  },
  {
    from: "Country",
    to: "Capability",
    type: "many-to-many",
    description: "Countries enable capabilities.",
  },
  {
    from: "Capability",
    to: "Provider",
    type: "many-to-many",
    description: "Capabilities are implemented by providers.",
  },
  {
    from: "Merchant",
    to: "Wallet",
    type: "one-to-many",
    description: "A merchant owns settlement wallets.",
  },
  {
    from: "Customer",
    to: "KycVerification",
    type: "one-to-many",
    description: "A customer has KYC verification attempts.",
  },
  {
    from: "Transaction",
    to: "TransactionEvent",
    type: "one-to-many",
    description: "A transaction has an immutable event log.",
  },
  {
    from: "Payment",
    to: "Refund",
    type: "one-to-many",
    description: "A payment can have multiple refunds.",
  },
  {
    from: "Payment",
    to: "Chargeback",
    type: "one-to-many",
    description: "A payment can have chargebacks.",
  },
  {
    from: "Provider",
    to: "ProviderHealthCheck",
    type: "one-to-many",
    description: "A provider has health checks over time.",
  },
  { from: "User", to: "Device", type: "one-to-many", description: "A user has multiple devices." },
  {
    from: "Merchant",
    to: "MerchantApiKey",
    type: "one-to-many",
    description: "A merchant has API keys.",
  },
];

// ---------------------------------------------------------------------------
// Partitioning strategy (Chapter 8)
// ---------------------------------------------------------------------------

export interface PartitionStrategy {
  table: string;
  partitionBy: "monthly" | "daily" | "yearly";
  reason: string;
  estimatedRowsPerMonth: string;
}

export const PARTITION_STRATEGIES: PartitionStrategy[] = [
  {
    table: "journal_entries",
    partitionBy: "monthly",
    reason: "Highest-volume table — every financial movement.",
    estimatedRowsPerMonth: "10M+",
  },
  {
    table: "transaction_events",
    partitionBy: "monthly",
    reason: "Append-only event log per transaction.",
    estimatedRowsPerMonth: "50M+",
  },
  {
    table: "payment_events",
    partitionBy: "monthly",
    reason: "Per-payment lifecycle events.",
    estimatedRowsPerMonth: "20M+",
  },
  {
    table: "audit_logs",
    partitionBy: "monthly",
    reason: "Every action — immutable compliance record.",
    estimatedRowsPerMonth: "100M+",
  },
  {
    table: "api_access_logs",
    partitionBy: "daily",
    reason: "High-volume API request logs.",
    estimatedRowsPerMonth: "500M+",
  },
  {
    table: "notifications",
    partitionBy: "monthly",
    reason: "Delivery logs grow fast.",
    estimatedRowsPerMonth: "30M+",
  },
  {
    table: "webhook_events",
    partitionBy: "monthly",
    reason: "Inbound webhooks from providers.",
    estimatedRowsPerMonth: "5M+",
  },
  {
    table: "outbox_events",
    partitionBy: "daily",
    reason: "Short-lived but high-volume.",
    estimatedRowsPerMonth: "50M+",
  },
  {
    table: "balance_snapshots",
    partitionBy: "monthly",
    reason: "Point-in-time snapshots for reconciliation.",
    estimatedRowsPerMonth: "1M+",
  },
  {
    table: "risk_events",
    partitionBy: "monthly",
    reason: "Risk engine evaluations.",
    estimatedRowsPerMonth: "40M+",
  },
  {
    table: "daily_metrics",
    partitionBy: "yearly",
    reason: "Pre-aggregated, low volume.",
    estimatedRowsPerMonth: "<1K",
  },
];

// ---------------------------------------------------------------------------
// Backup & DR strategy (Chapter 8)
// ---------------------------------------------------------------------------

export interface BackupStrategy {
  layer: string;
  frequency: string;
  retention: string;
  purpose: string;
}

export const BACKUP_STRATEGIES: BackupStrategy[] = [
  {
    layer: "Continuous WAL Archiving",
    frequency: "Real-time",
    retention: "7 days",
    purpose: "Point-in-time recovery (RPO ≤ 5 min).",
  },
  {
    layer: "Daily Backup",
    frequency: "Every 24h",
    retention: "30 days",
    purpose: "Daily snapshot for quick restore.",
  },
  {
    layer: "Weekly Snapshot",
    frequency: "Every 7 days",
    retention: "12 weeks",
    purpose: "Weekly checkpoint for audit.",
  },
  {
    layer: "Monthly Archive",
    frequency: "Every 30 days",
    retention: "7 years",
    purpose: "Long-term regulatory archive.",
  },
];

export const DR_TARGETS = {
  rpo: "≤ 5 minutes",
  rto: "≤ 30 minutes",
  description:
    "Recovery Point Objective: max 5 min of data loss. Recovery Time Objective: max 30 min downtime.",
};
