// TurboCore — TCQAF Quality Data (Chapter 14)
//
// Testing suites, certification records, quality metrics, release gates,
// provider simulations, load tests, chaos experiments.

import type {
  TestSuite,
  CertificationRecord,
  ProviderSandbox,
  QualityMetrics,
  ReleaseGate,
  ProviderSimulation,
  ReleaseCertification,
  LoadTestResult,
  ChaosExperiment,
} from "./types";

const NOW = new Date().toISOString();
const YESTERDAY = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();
const LAST_WEEK = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString();

// ---------------------------------------------------------------------------
// Test suites (Chapter 14 — 10 testing domains)
// ---------------------------------------------------------------------------

export const TEST_SUITES: TestSuite[] = [
  {
    id: "ts_unit",
    domain: "UNIT",
    name: "Unit Tests",
    description:
      "Fee calculation, FX conversion, ledger posting, risk scoring, wallet limits, routing decisions",
    totalTests: 22,
    passed: 22,
    failed: 0,
    skipped: 0,
    duration: 0.8,
    lastRun: YESTERDAY,
    status: "PASS",
  },
  {
    id: "ts_integration",
    domain: "INTEGRATION",
    name: "Integration Tests",
    description: "Payment → Ledger → Wallet → Notification flow verification",
    totalTests: 48,
    passed: 46,
    failed: 0,
    skipped: 2,
    duration: 12.4,
    lastRun: YESTERDAY,
    status: "PASS",
  },
  {
    id: "ts_contract",
    domain: "CONTRACT",
    name: "Contract Tests",
    description: "Provider API contract validation — detects breaking changes",
    totalTests: 85,
    passed: 83,
    failed: 0,
    skipped: 2,
    duration: 8.7,
    lastRun: YESTERDAY,
    status: "PASS",
  },
  {
    id: "ts_provider",
    domain: "PROVIDER_CERT",
    name: "Provider Certification",
    description: "Authentication, collections, payouts, refunds, webhooks, error handling",
    totalTests: 170,
    passed: 165,
    failed: 2,
    skipped: 3,
    duration: 45.2,
    lastRun: YESTERDAY,
    status: "PASS",
  },
  {
    id: "ts_security",
    domain: "SECURITY",
    name: "Security Tests",
    description:
      "SAST, DAST, dependency scanning, secret scanning, container scanning, API fuzzing",
    totalTests: 34,
    passed: 30,
    failed: 0,
    skipped: 4,
    duration: 67.8,
    lastRun: YESTERDAY,
    status: "PASS",
  },
  {
    id: "ts_performance",
    domain: "PERFORMANCE",
    name: "Performance Tests",
    description: "Load testing (100-10K TPS), stress testing, endurance testing",
    totalTests: 15,
    passed: 12,
    failed: 0,
    skipped: 3,
    duration: 180.5,
    lastRun: LAST_WEEK,
    status: "PASS",
  },
  {
    id: "ts_chaos",
    domain: "CHAOS",
    name: "Chaos Engineering",
    description: "Provider offline, Redis offline, DB replica loss — failover verification",
    totalTests: 8,
    passed: 7,
    failed: 0,
    skipped: 1,
    duration: 25.3,
    lastRun: LAST_WEEK,
    status: "PASS",
  },
  {
    id: "ts_compliance",
    domain: "COMPLIANCE",
    name: "Compliance Tests",
    description: "KYC, AML, audit, data retention, consent, access controls",
    totalTests: 22,
    passed: 22,
    failed: 0,
    skipped: 0,
    duration: 5.2,
    lastRun: YESTERDAY,
    status: "PASS",
  },
  {
    id: "ts_uat",
    domain: "UAT",
    name: "User Acceptance Tests",
    description: "Manual + automated UAT scenarios for customer flows",
    totalTests: 45,
    passed: 43,
    failed: 0,
    skipped: 2,
    duration: 30.0,
    lastRun: YESTERDAY,
    status: "PASS",
  },
  {
    id: "ts_regression",
    domain: "REGRESSION",
    name: "Regression Tests",
    description: "Automated regression on every merge request",
    totalTests: 120,
    passed: 118,
    failed: 0,
    skipped: 2,
    duration: 15.6,
    lastRun: YESTERDAY,
    status: "PASS",
  },
];

// ---------------------------------------------------------------------------
// Certification records (Chapter 14)
// ---------------------------------------------------------------------------

export const CERTIFICATIONS: CertificationRecord[] = [
  {
    id: "cert_paystack",
    type: "PROVIDER",
    target: "paystack",
    name: "Paystack Provider Certification",
    status: "CERTIFIED",
    score: 98,
    totalChecks: 10,
    passedChecks: 10,
    failedChecks: 0,
    lastVerifiedAt: YESTERDAY,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    certifiedBy: "ci-cd",
    checks: [
      { name: "Authentication", category: "AUTH", status: "PASS", durationMs: 120 },
      { name: "Card Collection", category: "COLLECTIONS", status: "PASS", durationMs: 340 },
      { name: "Bank Transfer", category: "COLLECTIONS", status: "PASS", durationMs: 280 },
      { name: "Virtual Account", category: "COLLECTIONS", status: "PASS", durationMs: 220 },
      { name: "Refund", category: "REFUNDS", status: "PASS", durationMs: 190 },
      { name: "Webhook Verification", category: "WEBHOOKS", status: "PASS", durationMs: 45 },
      { name: "Error Handling", category: "ERRORS", status: "PASS", durationMs: 150 },
      { name: "Retry Logic", category: "RETRIES", status: "PASS", durationMs: 300 },
      { name: "Rate Limit Handling", category: "RATE_LIMITS", status: "PASS", durationMs: 200 },
      {
        name: "Settlement Reconciliation",
        category: "SETTLEMENT",
        status: "PASS",
        durationMs: 500,
      },
    ],
  },
  {
    id: "cert_flutterwave",
    type: "PROVIDER",
    target: "flutterwave",
    name: "Flutterwave Provider Certification",
    status: "CERTIFIED",
    score: 95,
    totalChecks: 10,
    passedChecks: 10,
    failedChecks: 0,
    lastVerifiedAt: YESTERDAY,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    certifiedBy: "ci-cd",
    checks: [
      { name: "Authentication", category: "AUTH", status: "PASS", durationMs: 110 },
      { name: "Card Collection", category: "COLLECTIONS", status: "PASS", durationMs: 380 },
      { name: "Bank Transfer", category: "COLLECTIONS", status: "PASS", durationMs: 310 },
      { name: "Mobile Money", category: "COLLECTIONS", status: "PASS", durationMs: 260 },
      { name: "International Transfer", category: "PAYOUTS", status: "PASS", durationMs: 420 },
      { name: "Webhook Verification", category: "WEBHOOKS", status: "PASS", durationMs: 50 },
      { name: "Error Handling", category: "ERRORS", status: "PASS", durationMs: 180 },
      { name: "Retry Logic", category: "RETRIES", status: "PASS", durationMs: 320 },
      { name: "Rate Limit Handling", category: "RATE_LIMITS", status: "PASS", durationMs: 220 },
      {
        name: "Settlement Reconciliation",
        category: "SETTLEMENT",
        status: "PASS",
        durationMs: 480,
      },
    ],
  },
  {
    id: "cert_mpesa",
    type: "PROVIDER",
    target: "mpesa",
    name: "M-Pesa Provider Certification",
    status: "CERTIFIED",
    score: 96,
    totalChecks: 8,
    passedChecks: 8,
    failedChecks: 0,
    lastVerifiedAt: LAST_WEEK,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    certifiedBy: "ci-cd",
    checks: [
      { name: "OAuth2 Authentication", category: "AUTH", status: "PASS", durationMs: 200 },
      { name: "STK Push Collection", category: "COLLECTIONS", status: "PASS", durationMs: 350 },
      { name: "B2C Payout", category: "PAYOUTS", status: "PASS", durationMs: 400 },
      { name: "Balance Query", category: "BALANCE", status: "PASS", durationMs: 150 },
      {
        name: "Webhook (callback) Verification",
        category: "WEBHOOKS",
        status: "PASS",
        durationMs: 60,
      },
      { name: "Error Handling", category: "ERRORS", status: "PASS", durationMs: 170 },
      { name: "Retry Logic", category: "RETRIES", status: "PASS", durationMs: 280 },
      { name: "Timeout Handling", category: "ERRORS", status: "PASS", durationMs: 5000 },
    ],
  },
  {
    id: "cert_ledger",
    type: "LEDGER",
    target: "ledger",
    name: "Ledger Certification",
    status: "CERTIFIED",
    score: 100,
    totalChecks: 7,
    passedChecks: 7,
    failedChecks: 0,
    lastVerifiedAt: YESTERDAY,
    expiresAt: new Date(Date.now() + 90 * 24 * 60 * 60 * 1000).toISOString(),
    certifiedBy: "finance-engineering",
    checks: [
      {
        name: "Double Entry Balance",
        category: "LEDGER",
        status: "PASS",
        message: "All entries balance to ₦0.00",
      },
      {
        name: "Reversal Correctness",
        category: "LEDGER",
        status: "PASS",
        message: "Reversals create correct contra entries",
      },
      {
        name: "Refund Accounting",
        category: "LEDGER",
        status: "PASS",
        message: "Refunds debit correct accounts",
      },
      {
        name: "Chargeback Accounting",
        category: "LEDGER",
        status: "PASS",
        message: "Chargebacks create reserve entries",
      },
      {
        name: "FX Conversion",
        category: "LEDGER",
        status: "PASS",
        message: "FX gains/losses posted correctly",
      },
      {
        name: "Settlement Reconciliation",
        category: "LEDGER",
        status: "PASS",
        message: "0 unexplained variances in 30 days",
      },
      {
        name: "Journal Closure",
        category: "LEDGER",
        status: "PASS",
        message: "Period closure locks entries correctly",
      },
    ],
  },
  {
    id: "cert_ng",
    type: "COUNTRY",
    target: "NG",
    name: "Nigeria Country Certification",
    status: "CERTIFIED",
    score: 100,
    totalChecks: 5,
    passedChecks: 5,
    failedChecks: 0,
    lastVerifiedAt: YESTERDAY,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    certifiedBy: "qa-team",
    checks: [
      { name: "Cards (Paystack + Flutterwave)", category: "COLLECTIONS", status: "PASS" },
      { name: "Bank Transfer (Paystack + Monnify)", category: "COLLECTIONS", status: "PASS" },
      { name: "USSD Collection", category: "COLLECTIONS", status: "PASS" },
      { name: "Virtual Accounts", category: "COLLECTIONS", status: "PASS" },
      { name: "Settlement (T+1)", category: "SETTLEMENT", status: "PASS" },
    ],
  },
  {
    id: "cert_ke",
    type: "COUNTRY",
    target: "KE",
    name: "Kenya Country Certification",
    status: "CERTIFIED",
    score: 100,
    totalChecks: 4,
    passedChecks: 4,
    failedChecks: 0,
    lastVerifiedAt: LAST_WEEK,
    expiresAt: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString(),
    certifiedBy: "qa-team",
    checks: [
      { name: "M-Pesa STK Push", category: "MOBILE_MONEY", status: "PASS" },
      { name: "M-Pesa B2C Payout", category: "PAYOUTS", status: "PASS" },
      { name: "Card Payments", category: "COLLECTIONS", status: "PASS" },
      { name: "FX (KES↔USD)", category: "FX", status: "PASS" },
    ],
  },
];

// ---------------------------------------------------------------------------
// Provider sandbox management (Chapter 14)
// ---------------------------------------------------------------------------

export const PROVIDER_SANDBOXES: ProviderSandbox[] = [
  {
    providerCode: "paystack",
    displayName: "Paystack",
    sandboxAvailable: true,
    certificationStatus: "CERTIFIED",
    lastVerified: YESTERDAY,
    sandboxUrl: "https://api.paystack.co/sandbox",
    credentialsConfigured: true,
    testTransactionsRun: 145,
  },
  {
    providerCode: "flutterwave",
    displayName: "Flutterwave",
    sandboxAvailable: true,
    certificationStatus: "CERTIFIED",
    lastVerified: YESTERDAY,
    sandboxUrl: "https://api.flutterwave.com/v3/sandbox",
    credentialsConfigured: true,
    testTransactionsRun: 132,
  },
  {
    providerCode: "monnify",
    displayName: "Monnify",
    sandboxAvailable: true,
    certificationStatus: "CERTIFIED",
    lastVerified: YESTERDAY,
    sandboxUrl: "https://sandbox.monnify.com",
    credentialsConfigured: true,
    testTransactionsRun: 67,
  },
  {
    providerCode: "mpesa",
    displayName: "M-Pesa",
    sandboxAvailable: true,
    certificationStatus: "CERTIFIED",
    lastVerified: LAST_WEEK,
    sandboxUrl: "https://sandbox.safaricom.co.ke",
    credentialsConfigured: true,
    testTransactionsRun: 89,
  },
  {
    providerCode: "mtn-momo",
    displayName: "MTN MoMo",
    sandboxAvailable: true,
    certificationStatus: "CERTIFIED",
    lastVerified: LAST_WEEK,
    sandboxUrl: "https://sandbox.momodeveloper.mtn.com",
    credentialsConfigured: true,
    testTransactionsRun: 54,
  },
  {
    providerCode: "airtel-money",
    displayName: "Airtel Money",
    sandboxAvailable: true,
    certificationStatus: "CERTIFIED",
    lastVerified: LAST_WEEK,
    sandboxUrl: "https://sandbox.airtel.africa",
    credentialsConfigured: true,
    testTransactionsRun: 38,
  },
  {
    providerCode: "dojah",
    displayName: "Dojah",
    sandboxAvailable: true,
    certificationStatus: "CERTIFIED",
    lastVerified: YESTERDAY,
    sandboxUrl: "https://api.dojah.io/sandbox",
    credentialsConfigured: true,
    testTransactionsRun: 45,
  },
  {
    providerCode: "termii",
    displayName: "Termii",
    sandboxAvailable: true,
    certificationStatus: "CERTIFIED",
    lastVerified: YESTERDAY,
    sandboxUrl: "https://api.termii.com/sandbox",
    credentialsConfigured: true,
    testTransactionsRun: 28,
  },
  {
    providerCode: "resend",
    displayName: "Resend",
    sandboxAvailable: true,
    certificationStatus: "CERTIFIED",
    lastVerified: YESTERDAY,
    sandboxUrl: "https://api.resend.com/sandbox",
    credentialsConfigured: true,
    testTransactionsRun: 15,
  },
  {
    providerCode: "stripe",
    displayName: "Stripe",
    sandboxAvailable: true,
    certificationStatus: "PENDING",
    lastVerified: LAST_WEEK,
    sandboxUrl: "https://api.stripe.com/test",
    credentialsConfigured: true,
    testTransactionsRun: 12,
  },
  {
    providerCode: "wise",
    displayName: "Wise",
    sandboxAvailable: true,
    certificationStatus: "PENDING",
    lastVerified: LAST_WEEK,
    sandboxUrl: "https://api.sandbox.transferwise.tech",
    credentialsConfigured: true,
    testTransactionsRun: 8,
  },
];

// ---------------------------------------------------------------------------
// Quality metrics (Chapter 14)
// ---------------------------------------------------------------------------

export const QUALITY_METRICS: QualityMetrics = {
  codeCoverage: 87,
  branchCoverage: 72,
  escapedDefects: 0,
  regressionRate: 0,
  deploymentSuccessRate: 100,
  meanRecoveryTime: 22,
  providerCertificationScore: 97,
  securityFindings: 0,
  testPassRate: 99.1,
  totalTests: 569,
  totalPassing: 564,
  totalFailing: 2,
};

// ---------------------------------------------------------------------------
// Release gates (Chapter 14)
// ---------------------------------------------------------------------------

export const RELEASE_GATES: ReleaseGate[] = [
  {
    id: "g1",
    name: "Unit Tests Pass",
    description: "All unit tests must pass",
    category: "TEST",
    status: "PASSED",
    blocking: true,
    evidence: "22/22 passed in 0.8s",
    lastChecked: YESTERDAY,
  },
  {
    id: "g2",
    name: "Integration Tests Pass",
    description: "All integration tests must pass",
    category: "TEST",
    status: "PASSED",
    blocking: true,
    evidence: "46/48 passed (2 skipped)",
    lastChecked: YESTERDAY,
  },
  {
    id: "g3",
    name: "Contract Tests Pass",
    description: "Provider API contract tests must pass",
    category: "TEST",
    status: "PASSED",
    blocking: true,
    evidence: "83/85 passed (2 skipped)",
    lastChecked: YESTERDAY,
  },
  {
    id: "g4",
    name: "Ledger Tests Pass",
    description: "Ledger balancing tests must pass — zero tolerance for variances",
    category: "TEST",
    status: "PASSED",
    blocking: true,
    evidence: "7/7 passed — zero variances",
    lastChecked: YESTERDAY,
  },
  {
    id: "g5",
    name: "Security Scan Pass",
    description: "SAST + DAST + dependency scan must pass",
    category: "SECURITY",
    status: "PASSED",
    blocking: true,
    evidence: "30/34 passed (4 skipped) — 0 critical findings",
    lastChecked: YESTERDAY,
  },
  {
    id: "g6",
    name: "Provider Certification Valid",
    description: "All production providers must be certified",
    category: "CERTIFICATION",
    status: "PASSED",
    blocking: true,
    evidence: "10/11 certified (Stripe + Wise pending)",
    lastChecked: YESTERDAY,
  },
  {
    id: "g7",
    name: "Database Migration Validation",
    description: "All migrations must be backward compatible and reversible",
    category: "MIGRATION",
    status: "PASSED",
    blocking: true,
    evidence: "All migrations backward compatible",
    lastChecked: YESTERDAY,
  },
  {
    id: "g8",
    name: "Performance Smoke Test",
    description: "API latency under 500ms at 100 TPS",
    category: "PERFORMANCE",
    status: "PASSED",
    blocking: false,
    evidence: "avg 120ms, p95 280ms at 100 TPS",
    lastChecked: LAST_WEEK,
  },
  {
    id: "g9",
    name: "Operational Readiness",
    description: "Runbooks exist, on-call rotation set, alerts validated",
    category: "OPERATIONAL",
    status: "PASSED",
    blocking: false,
    evidence: "6 runbooks, on-call configured, 2 alerts firing",
    lastChecked: YESTERDAY,
  },
  {
    id: "g10",
    name: "Compliance Checks",
    description: "KYC, AML, audit retention validated",
    category: "TEST",
    status: "PASSED",
    blocking: true,
    evidence: "22/22 compliance tests passed",
    lastChecked: YESTERDAY,
  },
];

// ---------------------------------------------------------------------------
// Provider Simulation Framework (Chapter 14 — Production Enhancement)
// ---------------------------------------------------------------------------

export const PROVIDER_SIMULATIONS: ProviderSimulation[] = [
  {
    providerCode: "paystack",
    displayName: "Paystack",
    scenario: "SUCCESS",
    description: "Normal 200 success response",
    configuredResponse: { status: 200, delay: 150 },
    enabled: true,
  },
  {
    providerCode: "paystack",
    displayName: "Paystack",
    scenario: "TIMEOUT",
    description: "Simulate provider timeout (30s)",
    configuredResponse: { status: 408, delay: 30000 },
    enabled: false,
  },
  {
    providerCode: "paystack",
    displayName: "Paystack",
    scenario: "DUPLICATE_WEBHOOK",
    description: "Send the same webhook twice — idempotency test",
    configuredResponse: { status: 200, delay: 100 },
    enabled: false,
  },
  {
    providerCode: "flutterwave",
    displayName: "Flutterwave",
    scenario: "SUCCESS",
    description: "Normal 200 success response",
    configuredResponse: { status: 200, delay: 200 },
    enabled: true,
  },
  {
    providerCode: "flutterwave",
    displayName: "Flutterwave",
    scenario: "RATE_LIMITED",
    description: "Simulate 429 rate limit response",
    configuredResponse: { status: 429, delay: 100 },
    enabled: false,
  },
  {
    providerCode: "mpesa",
    displayName: "M-Pesa",
    scenario: "SUCCESS",
    description: "STK push success",
    configuredResponse: { status: 200, delay: 300 },
    enabled: true,
  },
  {
    providerCode: "mpesa",
    displayName: "M-Pesa",
    scenario: "SETTLEMENT_DELAY",
    description: "Simulate delayed settlement (T+3 instead of T+1)",
    configuredResponse: { status: 200, delay: 150 },
    enabled: false,
  },
  {
    providerCode: "stripe",
    displayName: "Stripe",
    scenario: "AUTH_FAILURE",
    description: "Simulate 401 authentication failure",
    configuredResponse: { status: 401, delay: 50 },
    enabled: false,
  },
];

// ---------------------------------------------------------------------------
// Release certification process (Chapter 14)
// ---------------------------------------------------------------------------

export const RELEASE_CERTIFICATION: ReleaseCertification = {
  id: "rc_1.1.0",
  version: "1.1.0",
  status: "APPROVED",
  startedAt: YESTERDAY,
  completedAt: YESTERDAY,
  approvedBy: "release-manager",
  stages: [
    {
      name: "Source Code",
      type: "SOURCE",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 2,
    },
    {
      name: "Build",
      type: "BUILD",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 89,
    },
    {
      name: "Unit Tests",
      type: "TEST",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 1,
    },
    {
      name: "Integration Tests",
      type: "TEST",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 12,
    },
    {
      name: "Provider Certification",
      type: "CERTIFICATION",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 45,
    },
    {
      name: "Security Validation",
      type: "SECURITY",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 68,
    },
    {
      name: "Performance Validation",
      type: "PERFORMANCE",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 180,
    },
    {
      name: "Ledger Certification",
      type: "CERTIFICATION",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 5,
    },
    {
      name: "Operational Readiness",
      type: "OPERATIONAL",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 3,
    },
    {
      name: "Release Approval",
      type: "APPROVAL",
      status: "PASSED",
      startedAt: YESTERDAY,
      completedAt: YESTERDAY,
      duration: 1,
    },
  ],
};

// ---------------------------------------------------------------------------
// Load tests (Chapter 14)
// ---------------------------------------------------------------------------

export const LOAD_TESTS: LoadTestResult[] = [
  {
    id: "lt_100",
    target: "100 TPS",
    tps: 100,
    duration: "5 min",
    avgResponseMs: 45,
    p95ResponseMs: 120,
    p99ResponseMs: 180,
    errorRate: 0,
    status: "PASS",
    runAt: LAST_WEEK,
  },
  {
    id: "lt_500",
    target: "500 TPS",
    tps: 500,
    duration: "5 min",
    avgResponseMs: 78,
    p95ResponseMs: 220,
    p99ResponseMs: 350,
    errorRate: 0,
    status: "PASS",
    runAt: LAST_WEEK,
  },
  {
    id: "lt_1000",
    target: "1,000 TPS",
    tps: 1000,
    duration: "5 min",
    avgResponseMs: 120,
    p95ResponseMs: 280,
    p99ResponseMs: 450,
    errorRate: 0.01,
    status: "PASS",
    runAt: LAST_WEEK,
  },
  {
    id: "lt_5000",
    target: "5,000 TPS",
    tps: 5000,
    duration: "3 min",
    avgResponseMs: 250,
    p95ResponseMs: 580,
    p99ResponseMs: 950,
    errorRate: 0.05,
    status: "PASS",
    runAt: LAST_WEEK,
  },
  {
    id: "lt_10000",
    target: "10,000 TPS",
    tps: 10000,
    duration: "1 min",
    avgResponseMs: 480,
    p95ResponseMs: 1200,
    p99ResponseMs: 2100,
    errorRate: 0.2,
    status: "PENDING",
    runAt: LAST_WEEK,
  },
];

// ---------------------------------------------------------------------------
// Chaos experiments (Chapter 14)
// ---------------------------------------------------------------------------

export const CHAOS_EXPERIMENTS: ChaosExperiment[] = [
  {
    id: "chaos_1",
    name: "Provider Offline (Paystack)",
    description: "Take Paystack adapter offline",
    failureInjected: "Paystack circuit breaker forced OPEN",
    expectedBehavior: "Routing engine auto-fails to Flutterwave → Monnify",
    actualBehavior: "Failover occurred in 1.2s — 0 customer impact",
    status: "PASS",
    runAt: LAST_WEEK,
  },
  {
    id: "chaos_2",
    name: "Redis Offline",
    description: "Kill Redis cluster",
    failureInjected: "Redis process killed on all nodes",
    expectedBehavior: "Platform continues with degraded caching — DB fallback",
    actualBehavior: "Platform continued — 15% latency increase, 0 failures",
    status: "PASS",
    runAt: LAST_WEEK,
  },
  {
    id: "chaos_3",
    name: "Database Replica Lost",
    description: "Kill PostgreSQL read replica",
    failureInjected: "Read replica process terminated",
    expectedBehavior: "Primary continues serving all traffic — reads redirected",
    actualBehavior: "Reads redirected to primary — 5% latency increase",
    status: "PASS",
    runAt: LAST_WEEK,
  },
  {
    id: "chaos_4",
    name: "Network Partition",
    description: "Network partition between K8s nodes",
    failureInjected: "iptables rules to block inter-node traffic",
    expectedBehavior: "Pods on isolated node restart on healthy nodes",
    actualBehavior: "Pods restarted in 45s — minimal impact",
    status: "PASS",
    runAt: LAST_WEEK,
  },
  {
    id: "chaos_5",
    name: "Event Queue Backlog",
    description: "Stop event consumers",
    failureInjected: "Paused all event queue consumers",
    expectedBehavior: "Queue grows but payments continue — alerts fire",
    actualBehavior: "Queue grew to 5000, alerts fired correctly, no payment failures",
    status: "PASS",
    runAt: LAST_WEEK,
  },
];

// ---------------------------------------------------------------------------
// Stats
// ---------------------------------------------------------------------------

export function getTcqafStats() {
  const totalTests = TEST_SUITES.reduce((s, t) => s + t.totalTests, 0);
  const totalPassed = TEST_SUITES.reduce((s, t) => s + t.passed, 0);
  const totalFailed = TEST_SUITES.reduce((s, t) => s + t.failed, 0);
  const totalSkipped = TEST_SUITES.reduce((s, t) => s + t.skipped, 0);
  const certifiedProviders = CERTIFICATIONS.filter(
    (c) => c.type === "PROVIDER" && c.status === "CERTIFIED"
  ).length;
  const blockingGates = RELEASE_GATES.filter((g) => g.blocking).length;
  const passedGates = RELEASE_GATES.filter((g) => g.status === "PASSED").length;

  return {
    testSuites: TEST_SUITES.length,
    totalTests,
    totalPassed,
    totalFailed,
    totalSkipped,
    testPassRate: totalTests > 0 ? Math.round((totalPassed / totalTests) * 1000) / 10 : 0,
    certifications: CERTIFICATIONS.length,
    certifiedProviders,
    providerSandboxes: PROVIDER_SANDBOXES.length,
    releaseGates: RELEASE_GATES.length,
    blockingGates,
    passedGates,
    allGatesPassed: passedGates === RELEASE_GATES.length,
    loadTests: LOAD_TESTS.length,
    chaosExperiments: CHAOS_EXPERIMENTS.length,
    providerSimulations: PROVIDER_SIMULATIONS.length,
    codeCoverage: QUALITY_METRICS.codeCoverage,
    escapedDefects: QUALITY_METRICS.escapedDefects,
  };
}
